# Generated by Django 3.2 on 2021-04-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='time',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(max_length=15),
        ),
    ]
