# Generated by Django 3.2.2 on 2021-05-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_auto_20210509_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='now',
        ),
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
