# Generated by Django 3.2.2 on 2021-05-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20210509_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='now',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
